data "aws_vpc" "default" {
  default = true
}
data "aws_subnets" "default" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }
}
module "test_instance" {
  source = "../"
  subnet_id = data.aws_subnets.default.ids[0]
}
 variable "name_prefix" {
   type = string
   description = "The prefix to apply to the beginning of names generated by this module."

 }
 variable "subnet_id" {
   type = string
   description = "The subnet ID where the instance will be launched."
 }
 variable "instance_type" {
   type = string
   description = "The instance type to launch."
 }
 variable "tags" {
   type = map(string)
 description = "Key/Value pairs to pass to AWS as Tags." 
  default = {}
 }

 resource "aws_instance" "hello_world" {
   ami = data.aws_ami.ubuntu.id
   subnet_id = var.subnet_id
   instance_type = var.instance_type

    tags = merge(var.tags, {
      Name = "${var.name_prefix}-instance"
    })
  }
  variable "instance_count" {
  type        = number
  description = "The number of instances to launch."
  default     = 0
  validation {
    condition     = can(parseint(tostring(var.instance_count), 10))                
    error_message = "The instance count must be a whole number."
  }
 
  validation {
    condition     = var.instance_count >= 0
    error_message = "The instance count can not be negative."
  }
}
 resource "aws_instance" "hello_world" {
  count         = var.instance_count
  ami           = data.aws_ami.ubuntu.id
  subnet_id     = var.subnet_id
  instance_type = var.instance_type
 
  tags = merge(var.tags, {
    Name = "${var.name_prefix}-${count.index}"
  })
}